document.addEventListener('DOMContentLoaded', async () => {
  const notice = document.querySelector('#notice'), form = document.querySelector('#application-form'); const user = await requireUser(); if (!user) return;
  try { const profile = await getProfile(user.id); document.querySelector('#full-name').value = profile?.full_name || ''; document.querySelector('#phone').value = profile?.phone || ''; form.hidden = false; } catch (error) { setNotice(notice, `Could not load your account: ${error.message}`, 'error'); return; }
  form.onsubmit = async event => { event.preventDefault(); const button = document.querySelector('#submit'); const image = document.querySelector('#image').files[0]; if (image && (image.size > 5 * 1024 * 1024 || !['image/jpeg','image/png','image/webp'].includes(image.type))) return setNotice(notice, 'Use a JPG, PNG, or WebP image smaller than 5 MB.', 'error'); toggleBusy(button, true, 'Submitting…'); setNotice(notice, '');
    const profileUpdate = { id:user.id, full_name:document.querySelector('#full-name').value.trim(), phone:document.querySelector('#phone').value.trim() }; const { error: profileError } = await db.from('profiles').upsert(profileUpdate); if (profileError) { toggleBusy(button,false); return setNotice(notice, profileError.message, 'error'); }
    let image_path = null; if (image) { const safeName = image.name.toLowerCase().replace(/[^a-z0-9._-]/g, '-'); image_path = `${user.id}/${crypto.randomUUID()}-${safeName}`; const { error } = await db.storage.from(INDEX_CONFIG.storageBucket).upload(image_path, image, { contentType:image.type, upsert:false }); if (error) { toggleBusy(button,false); return setNotice(notice, `Image upload failed: ${error.message}`, 'error'); } }
    const payload = { provider_id:user.id, business_name:document.querySelector('#business-name').value.trim(), service_name:document.querySelector('#service-name').value.trim(), category:document.querySelector('#category').value.trim(), city:document.querySelector('#city').value.trim(), website:document.querySelector('#website').value.trim() || null, description:document.querySelector('#description').value.trim(), image_path };
    const { error } = await db.from('service_applications').insert(payload); toggleBusy(button,false); if (error) return setNotice(notice, error.message, 'error'); form.reset(); setNotice(notice, 'Your service was submitted and is now pending review. We’ll publish it once approved.', 'success'); };
});
