document.addEventListener('DOMContentLoaded', () => {
  let mode = 'signin'; const form = document.querySelector('#auth-form'), notice = document.querySelector('#notice'); const submit = document.querySelector('#submit'); const params = new URLSearchParams(location.search);
  const showMode = next => { mode = next; document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.mode === next)); document.querySelector('#form-title').textContent = next === 'signup' ? 'Create your provider account' : 'Welcome back'; document.querySelector('#form-lede').textContent = next === 'signup' ? 'Create an account before submitting a service for review.' : 'Sign in to manage your service applications.'; submit.textContent = next === 'signup' ? 'Create account' : 'Sign in'; document.querySelector('#signup-help').hidden = next !== 'signup'; document.querySelector('#password').autocomplete = next === 'signup' ? 'new-password' : 'current-password'; setNotice(notice, ''); };
  document.querySelectorAll('.tab').forEach(tab => tab.onclick = () => showMode(tab.dataset.mode));
  form.onsubmit = async e => { e.preventDefault(); const email = document.querySelector('#email').value.trim(); const password = document.querySelector('#password').value; toggleBusy(submit, true); setNotice(notice, ''); let result;
    if (mode === 'signup') result = await db.auth.signUp({ email, password, options: { emailRedirectTo: new URL('auth.html', location.href).href } }); else result = await db.auth.signInWithPassword({ email, password });
    toggleBusy(submit, false); if (result.error) return setNotice(notice, result.error.message, 'error'); if (mode === 'signup' && !result.data.session) return setNotice(notice, 'Account created. Check your email to confirm it, then sign in.', 'success'); if (params.get('next')) { location.href = params.get('next'); return; } try { location.href = await isAdmin() ? 'admin.html' : 'apply.html'; } catch (_) { location.href = 'apply.html'; } };
  document.querySelector('#forgot-link').onclick = e => { e.preventDefault(); form.hidden = true; document.querySelector('.tab-row').hidden = true; document.querySelector('#forgot-form').hidden = false; document.querySelector('#form-title').textContent = 'Reset your password'; document.querySelector('#form-lede').textContent = 'We’ll email you a secure reset link.'; setNotice(notice, ''); };
  document.querySelector('#back-link').onclick = e => { e.preventDefault(); location.reload(); };
  document.querySelector('#forgot-form').onsubmit = async e => { e.preventDefault(); const button = document.querySelector('#reset-submit'); toggleBusy(button, true); const { error } = await db.auth.resetPasswordForEmail(document.querySelector('#reset-email').value.trim(), { redirectTo: new URL('reset-password.html', location.href).href }); toggleBusy(button, false); setNotice(notice, error ? error.message : 'If that address has an account, a reset link has been sent.', error ? 'error' : 'success'); };
});
