const providers = [
 {id:'demo-north-star',name:'North Star Studio',cat:'Web & apps',place:'Austin, TX',rating:'4.9',reviews:'24',desc:'Strategy, design and websites for independent businesses with big ambitions.',image:'assets/studio.jpg',featured:true},
 {id:'demo-aster',name:'Aster & Field',cat:'Home & repair',place:'Portland, OR',rating:'5.0',reviews:'18',desc:'Landscape design that turns everyday outdoor spaces into places you want to linger.',image:'assets/home.jpg'},
 {id:'demo-soft-focus',name:'Soft Focus',cat:'Health & wellness',place:'Brooklyn, NY',rating:'4.8',reviews:'31',desc:'A restorative studio for massage, movement and slower days.',image:'assets/wellness.jpg'},
 {id:'demo-good-company',name:'Good Company',cat:'Design & creative',place:'Chicago, IL',rating:'4.9',reviews:'16',desc:'Photography and art direction for people building something meaningful.',image:'assets/events.jpg'},
 {id:'demo-clear-path',name:'The Clear Path',cat:'Business & professional',place:'Los Angeles, CA',rating:'4.9',reviews:'42',desc:'Practical legal counsel for creative, owner-led businesses.',image:'assets/legal.jpg'},
 {id:'demo-made-to-learn',name:'Made to Learn',cat:'Education & tutoring',place:'Online',rating:'5.0',reviews:'12',desc:'Patient, curious coaching for students finding their own way forward.',image:'assets/portfolio-2.jpg'}
];
let supabaseClient=null, currentUser=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function card(p){return `<article class="listing-card"><a class="card-image" href="provider.html?id=${encodeURIComponent(p.id)}"><img src="${esc(p.image||'assets/studio.jpg')}" alt="${esc(p.name)}">${p.featured?'<span>Featured</span>':''}</a><div class="card-body"><div class="card-topline"><p>${esc(p.cat)}</p><button class="heart" data-provider-id="${esc(p.id)}" aria-label="Save ${esc(p.name)}">♡</button></div><h3><a href="provider.html?id=${encodeURIComponent(p.id)}">${esc(p.name)}</a></h3><p class="card-desc">${esc(p.desc)}</p><div class="card-footer"><span>★ ${esc(p.rating||'—')} <small>(${esc(p.reviews||'0')})</small></span><span>${esc(p.place||'')}</span></div></div></article>`}
async function loadRealProviders(){
 if(!supabaseClient)return [];
 const {data,error}=await supabaseClient.from('providers').select('*').order('created_at',{ascending:false});
 if(error){console.warn('Providers could not be loaded:',error.message);return []}
 return (data||[]).map(p=>({id:p.id,name:p.name||p.title||'Unnamed provider',cat:p.category||'Other',place:p.location||'',rating:p.rating||'—',reviews:p.review_count||0,desc:p.description||'',image:p.image_url||'assets/studio.jpg',website:p.website,owner_id:p.owner_id,featured:p.featured}));
}
async function initSupabase(){
 if(!window.supabase||!window.THE_INDEX_SUPABASE_URL)return;
 supabaseClient=window.supabase.createClient(window.THE_INDEX_SUPABASE_URL,window.THE_INDEX_SUPABASE_KEY);
 const {data}=await supabaseClient.auth.getSession(); currentUser=data.session?.user||null; updateAuthUI();
 supabaseClient.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;updateAuthUI();});
}
function updateAuthUI(){document.querySelectorAll('.js-list').forEach(b=>{b.textContent=currentUser?'List your business ↗':'Sign in to list your business ↗';});}
function openAuth(){const d=$('#authDialog');if(d)d.showModal()}
async function ensureProfile(){if(!currentUser||!supabaseClient)return;const name=currentUser.user_metadata?.full_name||currentUser.email?.split('@')[0]||'Index member';await supabaseClient.from('profiles').upsert({id:currentUser.id,name,email:currentUser.email},{onConflict:'id'});}
function bindHearts(root=document){root.querySelectorAll('.heart').forEach(b=>b.onclick=async e=>{e.preventDefault();e.stopPropagation();if(!currentUser){openAuth();return}const id=b.dataset.providerId;if(String(id).startsWith('demo-')){b.classList.toggle('saved');b.textContent=b.classList.contains('saved')?'♥':'♡';toast('Demo listing saved for this session');return}const {data:existing}=await supabaseClient.from('favourites').select('provider_id').eq('provider_id',id).eq('user_id',currentUser.id).maybeSingle();if(existing){await supabaseClient.from('favourites').delete().eq('provider_id',id).eq('user_id',currentUser.id);b.textContent='♡';toast('Removed from favourites')}else{await supabaseClient.from('favourites').insert({provider_id:id,user_id:currentUser.id});b.textContent='♥';toast('Saved to favourites')}})}
async function initDirectory(){const grid=$('#listingGrid'),empty=$('#emptyState'),filter=$('#categoryFilter'),input=$('#directorySearch'),note=$('#resultsNote');if(!grid)return;let all=[...providers,...await loadRealProviders()];let query='',category='All';function render(){const r=all.filter(p=>(category==='All'||p.cat===category)&&(`${p.name} ${p.cat} ${p.desc} ${p.place}`.toLowerCase().includes(query.toLowerCase())));grid.innerHTML=r.map(card).join('');empty.hidden=!!r.length;note.textContent=r.length?`${r.length} ${r.length===1?'business':'businesses'} ${category==='All'?'to discover':'in '+category}.`:'No results for that search.';bindHearts(grid)}
 function setSearch(v){query=v;input.value=v;render();$('#directory')?.scrollIntoView({behavior:'smooth',block:'start'})}
 $('#searchForm').onsubmit=e=>{e.preventDefault();setSearch(input.value.trim())};document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>setSearch(b.dataset.search));document.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>{category=a.dataset.category;filter.value=category;render()});filter.onchange=()=>{category=filter.value;render()};$('#clearSearch').onclick=()=>{query='';category='All';filter.value='All';input.value='';render()};render()}
async function listBusiness(){if(!currentUser){openAuth();return}await ensureProfile();$('#listDialog')?.showModal()}
function initDialogs(){document.querySelectorAll('.js-list').forEach(b=>b.onclick=listBusiness);const contact=$('#contactButton');if(contact)contact.onclick=()=>{if(!currentUser)openAuth();else $('#contactDialog').showModal()};const auth=$('#authForm');if(auth)auth.onsubmit=handleAuth;const signOut=$('#signOutButton');if(signOut)signOut.onclick=async()=>{await supabaseClient.auth.signOut();toast('Signed out')};document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{if(d.returnValue==='default')toast(d.id==='contactDialog'?'Message saved — messaging backend will be connected next.':d.id==='listDialog'?'Listing form ready — database fields will be submitted next.':'Saved.')}))}
async function handleAuth(e){e.preventDefault();if(!supabaseClient)return;const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||!password)return;const mode=$('#authMode').value;let result=mode==='signup'?await supabaseClient.auth.signUp({email,password}):await supabaseClient.auth.signInWithPassword({email,password});if(result.error){toast(result.error.message);return}currentUser=result.data.user;await ensureProfile();$('#authDialog').close();toast(mode==='signup'?'Account created':'Signed in');}
async function initProfile(){const params=new URLSearchParams(location.search),id=params.get('id')||'demo-north-star';if(!document.querySelector('.profile'))return;if(id.startsWith('demo-'))return;const {data,error}=await supabaseClient.from('providers').select('*').eq('id',id).maybeSingle();if(error||!data){toast('Provider could not be loaded');return}document.title=`${data.name||data.title} — The Index`;const set=(sel,val)=>{const el=$(sel);if(el)el.textContent=val||''};set('.profile-heading h1',data.name||data.title);set('.profile-lede',data.description);set('.profile-heading .eyebrow',`${data.category||'Other'} • ${data.location||''}`);const img=$('.hero-image img');if(img&&data.image_url)img.src=data.image_url;const website=$('.website');if(website&&data.website){website.href=data.website;website.target='_blank'} }
async function init(){await initSupabase();initDialogs();await initDirectory();await initProfile();bindHearts()}
document.addEventListener('DOMContentLoaded',init);
