const providers = [
 {name:'North Star Studio',cat:'Web & apps',place:'Austin, TX',rating:'4.9',reviews:'24',desc:'Strategy, design and websites for independent businesses with big ambitions.',image:'assets/studio.jpg',featured:true},
 {name:'Aster & Field',cat:'Home & repair',place:'Portland, OR',rating:'5.0',reviews:'18',desc:'Landscape design that turns everyday outdoor spaces into places you want to linger.',image:'assets/home.jpg'},
 {name:'Soft Focus',cat:'Health & wellness',place:'Brooklyn, NY',rating:'4.8',reviews:'31',desc:'A restorative studio for massage, movement and slower days.',image:'assets/wellness.jpg'},
 {name:'Good Company',cat:'Design & creative',place:'Chicago, IL',rating:'4.9',reviews:'16',desc:'Photography and art direction for people building something meaningful.',image:'assets/events.jpg'},
 {name:'The Clear Path',cat:'Business & professional',place:'Los Angeles, CA',rating:'4.9',reviews:'42',desc:'Practical legal counsel for creative, owner-led businesses.',image:'assets/legal.jpg'},
 {name:'Made to Learn',cat:'Education & tutoring',place:'Online',rating:'5.0',reviews:'12',desc:'Patient, curious coaching for students finding their own way forward.',image:'assets/portfolio-2.jpg'}
];
const $ = s => document.querySelector(s); const esc = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(p){return `<article class="listing-card"><a class="card-image" href="provider.html"><img src="${p.image}" alt="${esc(p.name)}">${p.featured?'<span>Featured</span>':''}</a><div class="card-body"><div class="card-topline"><p>${esc(p.cat)}</p><button class="heart" aria-label="Save ${esc(p.name)}">♡</button></div><h3><a href="provider.html">${esc(p.name)}</a></h3><p class="card-desc">${esc(p.desc)}</p><div class="card-footer"><span>★ ${p.rating} <small>(${p.reviews})</small></span><span>${esc(p.place)}</span></div></div></article>`}
function toast(text){const t=$('#toast'); if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function bindHearts(root=document){root.querySelectorAll('.heart').forEach(b=>b.onclick=()=>{let active=b.classList.toggle('saved');b.textContent=active?'♥':'♡';toast(active?'Saved to favourites':'Removed from favourites')})}
function initDirectory(){const grid=$('#listingGrid'), empty=$('#emptyState'), filter=$('#categoryFilter'), input=$('#directorySearch'), note=$('#resultsNote');if(!grid)return;let query='',category='All';function render(){let r=providers.filter(p=>(category==='All'||p.cat===category)&&(`${p.name} ${p.cat} ${p.desc}`.toLowerCase().includes(query.toLowerCase())));grid.innerHTML=r.map(card).join('');empty.hidden=!!r.length;note.textContent=r.length?`${r.length} ${r.length===1?'business':'businesses'} ${category==='All'?'to discover':'in '+category}.`:'No results for that search.';bindHearts(grid)}function setSearch(v){query=v;input.value=v;render();document.querySelector('#directory').scrollIntoView({behavior:'smooth',block:'start'})}$('#searchForm').onsubmit=e=>{e.preventDefault();setSearch(input.value.trim())};document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>setSearch(b.dataset.search));document.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>{category=a.dataset.category;filter.value=category;render()});filter.onchange=()=>{category=filter.value;render()};$('#clearSearch').onclick=()=>{query='';category='All';filter.value='All';input.value='';render()};render()}
function initDialogs(){document.querySelectorAll('.js-list').forEach(b=>b.onclick=()=>$('#listDialog').showModal());const contact=$('#contactButton');if(contact)contact.onclick=()=>$('#contactDialog').showModal();document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>{if(d.returnValue==='default')toast(d.id==='contactDialog'?'Demo message sent — no message was actually delivered.':'Demo listing saved locally for this session.')}))}
function initProfile(){const grid=$('#relatedGrid');if(grid){grid.innerHTML=providers.filter(p=>p.name!=='North Star Studio').slice(0,3).map(card).join('');bindHearts(grid)}const save=$('#saveButton');if(save)save.onclick=()=>{const on=save.classList.toggle('saved');save.textContent=on?'♥ Saved to favourites':'♡ Save to favourites';toast(on?'Saved to favourites':'Removed from favourites')}}
document.addEventListener('DOMContentLoaded',()=>{initDirectory();initDialogs();initProfile();bindHearts()});
